// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-redesign/CompanionLed.tsx": () => import("../components/mockups/home-redesign/CompanionLed.tsx"),
  "./components/mockups/home-redesign/ConfidentClinic.tsx": () => import("../components/mockups/home-redesign/ConfidentClinic.tsx"),
  "./components/mockups/home-redesign/LateNight.tsx": () => import("../components/mockups/home-redesign/LateNight.tsx"),
  "./components/mockups/home-redesign/QuietMorning.tsx": () => import("../components/mockups/home-redesign/QuietMorning.tsx"),
  "./components/mockups/home-redesign/SingleBrief.tsx": () => import("../components/mockups/home-redesign/SingleBrief.tsx"),
  "./components/mockups/home-redesign/TimelineHome.tsx": () => import("../components/mockups/home-redesign/TimelineHome.tsx")
};
